name: Master Branch Workflow

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  DOCKER_IMAGE: ${{ env.DOCKER_REGISTRY }}/jasekirby/ghat/ghat
  DOCKER_IMAGE_LATEST: ${{ env.DOCKER_IMAGE }}:latest
  DOCKER_IMAGE_SHA: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: build docker image
      run: |
        docker build -t $DOCKER_IMAGE_SHA .

    - name: set version
      id: set_version
      run: |
        VERSION=v$(cat VERSION)
        echo "::set-env name=VERSION::$VERSION"
        echo "::set-output name=version::$VERSION"

    - name: create release
      id: create_release
      if: github.event_name == 'push'
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.set_version.outputs.version }}
        release_name: ${{ steps.set_version.outputs.version }}

    - name: upload version file release asset
      id: upload_release_asset
      if: github.event_name == 'push'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: VERSION
        asset_name: VERSION
        asset_content_type: text/plain

    - name: tag and publish docker image
      if: github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login -u publisher -p $GITHUB_TOKEN $DOCKER_REGISTRY
        DOCKER_IMAGE_VERSION=$DOCKER_IMAGE:$VERSION
        docker tag $DOCKER_IMAGE_SHA $DOCKER_IMAGE_VERSION
        docker push $DOCKER_IMAGE_VERSION
        docker tag $DOCKER_IMAGE_SHA $DOCKER_IMAGE_LATEST
        docker push $DOCKER_IMAGE_LATEST

  # testimg:
  #   name: testimg
  #   needs: build
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ${{ jobs.build.steps.}}
  #   steps:

  #   - name: view README
  #     if: github.event_name == 'push'
