name: Master Branch Workflow

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  DOCKER_REGISTRY: dock-reg.company.com
  DOCKER_REPO: turtle-team/app

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Build Image # run on both master branch changes and pull requests against master
      run: |
        echo "building image => $DOCKER_REGISTRY/$DOCKER_REPO:$GITHUB_SHA"

    - name: Set VERSION Environment Variable
      run: |
        VERSION=v$(cat VERSION)
        echo "::set-env name=VERSION::$VERSION"

    - name: Print VERSION
      run: echo $VERSION

    - name: Tag and Publish # only run master branch changes
      if: github.event_name == 'push'
      run: |
        git tag $VERSION
        git push --tags
        echo "tagging image => $DOCKER_REGISTRY/$DOCKER_REPO:$GITHUB_SHA to $DOCKER_REGISTRY/$DOCKER_REPO:$VERSION"
        